version: '2'

services:
    web:
        build: .
        image: item-catalog
        ports:
            - '5000:5000'
        links:
            - postgres

    postgres:
        image: postgres
        ports:
            - '5432:5432'
      volumes:
          - ./db/sample_catalog.sql:/docker-entrypoint-initdb.d/itemcatalog.sql
