version: '2'

services:
    web:
        build: .
        image: item-catalog
        ports:
            - '5000:5000'
        depends_on:
            - postgres

    postgres:
        image: postgres
        ports:
            - '5432:5432'
        volumes:
            - ./db/postgres.sample_catalog.sql:/docker-entrypoint-initdb.d/itemcatalog.sql
        environment:
            POSTGRES_USER: pgdbuser
            POSTGRES_PASSWORD: pgpassword
            POSTGRES_DB: itemcatalog
