---

- name: Clone project repository
  subversion:
    repo: "{{ git_repo }}"
    dest: "{{ project_path }}"

- name: Install Python packages
  pip:
    requirements: "{{ project_path }}/requirements.txt"
