---

- name: Clone project repository
  subversion:
    repo: "{{ git_repo }}"
    dest: "{{ project_path }}"

- name: Install Python packages
  pip:
    requirements: "{{ project_path }}/requirements.txt"

- name: Copy upstart script
  shell: cp /itemcatalog/itemcatalog.conf /etc/init
  args:
    creates: /etc/init/itemcatalog.conf

- name: Start itemcatalog service
  service:
    name: itemcatalog
    state: started
