---

- name: Install packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: present
  with_items:
    - python
    - python-pip
    - python-psycopg2

- include: app.yml
